dark_theme: true
autoload_model: false
max_new_tokens: 600
max_new_tokens_min: 1
max_new_tokens_max: 4096
seed: -1
stop_at_newline: true
add_bos_token: true
ban_eos_token: false
skip_special_tokens: true
truncation_length: 2048
truncation_length_min: 0
truncation_length_max: 16384
mode: notebook
start_with: ''
chat_style: cai-chat
instruction_template: None
chat-instruct_command: 'Continue the chat dialogue below. Write a single reply for
  the character "<|character|>".


  <|prompt|>'
chat_generation_attempts: 1
chat_generation_attempts_min: 1
chat_generation_attempts_max: 10
default_extensions: [
- silero_tts
]
chat_default_extensions:
- gallery
- silero_tts
preset: 'Divine Intellect'
prompt: QA