do_sample: true
temperature: 0.7
top_p: 0.9
typical_p: 1
epsilon_cutoff: 0
eta_cutoff: 0
repetition_penalty: 1.49
repetition_penalty_range: 0
encoder_repetition_penalty: 1.02
top_k: 20
min_length: 0
no_repeat_ngram_size: 1
num_beams: 1
penalty_alpha: 0.28
length_penalty: 1
early_stopping: true
mirostat_mode: 0
mirostat_tau: 5
mirostat_eta: 0.1
tfs: 1
top_a: 0
