do_sample: true
temperature: 0.7
top_p: 0.5
typical_p: 0.19
epsilon_cutoff: 0
eta_cutoff: 0
repetition_penalty: 1.1
repetition_penalty_range: 32
encoder_repetition_penalty: 1
top_k: 0
min_length: 0
no_repeat_ngram_size: 3
num_beams: 1
penalty_alpha: 0
length_penalty: 1
early_stopping: false
mirostat_mode: 0
mirostat_tau: 5
mirostat_eta: 0.1
tfs: 1
top_a: 0
